### PR TITLE
Added the Symfony Guard component

### PR DESCRIPTION
**Pull request by javiereguiluz**
Before merging this change, we need to settle on the official name of the component:

  * The URL is "security-guard" (https://github.com/symfony/security-guard)
  * The title of the component doc is "Security Component - Guard"
  * The description of the component talks about "The Guard component"

cc @weaverryan

### CODE REVIEW

**Comment by javiereguiluz** [comment]
@weaverryan sorry for being so pushy, but I'd like to add the information of your great component as soon as possible. Which one of the following should be the component name?

  * `Guard`
  * `SecurityGuard`

Thanks!

**Comment by weaverryan** [comment]
`Guard` or `Guard Auth` (still short, a little more descriptive). You're fast for getting this updated.

**Comment by javiereguiluz** [comment]
I don't know what to do here. Let's ask @fabpot: do you prefer `Guard` or `GuardAuth` as the component name? Thanks.

**Comment by fabpot** [comment]
I would use `Guard`

**Comment by javiereguiluz** [comment]
Then, `Guard` it is. Merged. Thanks.

**Pull request closed without merging**
