### PR TITLE
add bowerphp project

### PR DESCRIPTION
**Pull request by garak**

### CODE REVIEW

**Comment by javiereguiluz** [comment]
@garak thanks for proposing to add a new Symfony-based project. Your pull request looks good ... but there are some steps missing. We've just added some [basic instructions](https://github.com/symfony/symfony-marketing#how-to-add-a-project-to-the-list-of-projects-made-with-symfony) that explain how to add a project. As you can see, here we're missing the project logo and also adding the project to `projects/_projects.yml` file. Thanks!

**Comment by garak** [comment]
Well, I see that many projects are without logo. Indeed, I see online that only the first 9 projects have a logo, all the others don't.

**Comment by javiereguiluz** [comment]
@garak if the project doesn't have a logo, you can leave it empty. But most of the projects define a logo and we show it in the detail page. For example: http://symfony.com/projects/sylius, http://symfony.com/projects/sonataproject, http://symfony.com/projects/grav

**Comment by garak** [comment]
OK, logo added.

**Comment by javiereguiluz** [comment]
@garak thanks for adding the logo. However, I'm closing this PR in favor of #341 which adds the needed files to merge the project. I reused your original commit so you'll get full credit for your work. Thanks!

**Pull request closed without merging**
