### PR TITLE
updated sulu

### PR DESCRIPTION
**Pull request by danrot**
Changed the name of the project since we do not longer call ourselves a CMF, and added a logo.

### CODE REVIEW

**Comment by fabpot** [comment]
I think there are other references to sulucmf that needs to be changed.

**Comment by danrot** [comment]
@fabpot Where are these references? In this repository I could only find a third file with the slovenian translation, which I moved now, but I can't translate it...

**Comment by danrot** [comment]
Ok, found another one, sry about that. Is now also fixed in the `_projects.yml` file.

**Comment by danrot** [comment]
@fabpot Another question, what do we have to do to become a major project?

**Pull request merged**
