### PR TITLE
Slack community

### PR DESCRIPTION
**Pull request by Ricknox**
| Q             | A
| ------------- | ---
| New page?  | yes
| Deprecations? | no

This adds the 'Slack' page including the invite url to join the Slack community of Symfony. I have added two languages: `en` and `nl`. Feel free to accept/improve/decline this pull request.

Note; It is unsure to say if this is a official slack.

### CODE REVIEW

**Comment by iltar** [comment]
Currently IRC has ~3x less people online, but is way more active than slack. I'm not sure (based on personal experience so far), if slack is the right solution to this.

**Comment by Ricknox** [comment]
I am not sure either but I am just throwing this pull request out in the wild to see if will be a right solution. So far reading all the messages across different channels, there is community support. I guess if more and more people join, it might be the right solution.

**Comment by rvanlaak** [comment]
Slack isn't as active as IRC yet, but as they officially support the Slack channel now I think this should be the way to go. I'm not sure if Slack will be replacing IRC eventually though.

**Comment by javiereguiluz** [comment]
Comment: we're thinking about starting to promote Slack on symfony.com/support. But we're going to start slowly because Slack is still experimental. So we're not going to add this new page in the short term ... but we'll do that eventually. Thanks!

**Comment by fabpot** [comment]
Closing as this will be done on symfony.com directly.

**Comment by Ricknox** [comment]
Good to hear you guys are implementing this as a feature. Thank you for your time and sorry for any inconvenience this may caused you or somebody else by taking up your time.

proposal-3

**Pull request closed without merging**
