### PR TITLE
add VarDumper component summary

### PR DESCRIPTION
**Pull request by xabbuh**

### CODE REVIEW

**Comment by glensc** [comment]
http://symfony.com/components and http://symfony.com/components/VarDumper still broken. any ideas when the fix lands?

**Comment by xabbuh** [comment]
ping @javiereguiluz

**Comment by javiereguiluz** [comment]
@xabbuh @glensc VarDumper has been fixed in https://github.com/symfony/symfony-marketing/pull/293  Thanks for reporting this error!

**Comment by xabbuh** [comment]
@javiereguiluz Oh shit, what a stupid mistake. Thanks for fixing.

**Comment by glensc** [comment]
but website still not updated!

**Comment by xabbuh** [comment]
It's updated now.

**Pull request merged**
