### PR TITLE
Adding Contao to projects list

### PR DESCRIPTION
**Pull request by aschempp**
Contao is one of the leading open source CMS in Germany (D-A-CH). It recently won a comparison of content management systems by the print magazin [Screenguide](http://screengui.de/28).

Starting with version 4 (released spring 2015), Contao is using the Symfony full stack framework and steadily migrating the existing framework to Symfony components. We think it's a great example on how a legacy application can be integrated with Symfony; Contao 4 is still mostly BC as we're starting to embrace the Symfony BC promise.

I didn't know where to put Contao in the list of projects, or how to contribute text description for the project, maybe you can point that out?

### CODE REVIEW

**Comment by javiereguiluz** [comment]
@aschempp thanks for proposing to add a new project and sorry for the delay answering you.

Before adding this project, two more changes are needed:

  * Add the project at the end of this file: https://github.com/symfony/symfony-marketing/blob/master/projects/_projects.yml#L66  We'll review the highlighted/major/minor list soon, so for now we'll put it in the "minor" list and review it later. Thanks!
  * Create a `projects/en/contao.html.twig` file with a paragraph describing the project. If needed, check out the [Grav project description](https://github.com/symfony/symfony-marketing/blob/master/projects/en/grav.html.twig) which is similar to Contao and it was recently added.

**Comment by aschempp** [comment]
I have updated/created the respective files. Shall we also add a german description?

**Comment by javiereguiluz** [comment]
@aschempp there is no need to translate the description because we always merge it in English first and then, i fthere is interest, others translate the projects. Thanks.

**Comment by javiereguiluz** [comment]
@aschempp thanks for adding this project. I've just merged the change and it will appear on symfony.com starting from tomorrow. Thanks!

**Pull request closed without merging**
